INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 214', '2009', 'Urban Policy Analysis', '3', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 321', '2009', 'Planning for Social Equity', '3', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 124', '2009', 'Planning Law and Ethics', '3', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 217', '2009', 'Planning Law and Ethics', '4', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 113', '2009', 'Urban Governance and Management', '2', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 336', '2009', 'Land Use Planning', '2', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 138', '2009', 'Housing and Community Development', '2', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 335', '2009', 'Rural-Urban Interaction', '3', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 111', '2009', 'Introduction to Urban and Regional Planning', '4', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 117', '2009', 'Urban Informal Settlements', '2', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 313', '2009', 'Urban Design and Development', '4', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 325', '2009', 'Urban Regeneration', '4', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 127', '2009', 'Regional Development Planning', '2', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 318', '2009', 'Urban Regeneration', '2', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 237', '2009', 'Smart Cities and Technology in Planning', '4', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 238', '2009', 'Landscape and Open Space Planning', '2', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 227', '2009', 'Disaster Resilient Cities', '3', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 234', '2009', 'Urban Sociology', '2', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 236', '2009', 'Housing and Community Development', '4', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 316', '2009', 'Rural-Urban Interaction', '2', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 315', '2009', 'Housing Policy and Planning', '3', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 126', '2009', 'Economic Development Strategies', '2', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 224', '2009', 'Urban Design and Development', '2', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 332', '2009', 'Urban Health and Wellbeing', '2', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 228', '2009', 'Urban Informal Settlements', '2', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 121', '2009', 'Transportation Planning', '2', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 233', '2009', 'Sustainable Urban Planning', '2', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 121', '2009', 'History of Mathematics', '2', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 312', '2002', 'Fourier Analysis', '4', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 124', '2001', 'Discrete Mathematics', '3', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 332', '2002', 'Probability Theory', '4', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 118', '2004', 'Number Theory and Cryptography', '4', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 321', '2002', 'Fourier Analysis', '4', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 225', '2008', 'Number Theory', '4', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 125', '2008', 'Discrete Mathematics', '4', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 236', '2003', 'Mathematical Modeling', '2', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 322', '2004', 'Combinatorics', '3', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 138', '2008', 'Nonlinear Dynamics', '2', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 327', '2009', 'Representation Theory', '2', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 115', '2004', 'Calculus II', '2', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 114', '2006', 'Linear Algebra', '4', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 217', '2003', 'Measure Theory', '2', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 215', '2004', 'Mathematical Computing', '2', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 311', '2008', 'Combinatorics', '2', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 128', '2002', 'Probability Theory', '4', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 335', '2005', 'Calculus II', '2', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 328', '2006', 'Statistical Inference', '2', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 222', '2002', 'Complex Variables', '2', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 131', '2002', 'Geometry and Topology', '3', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 126', '2004', 'Mathematical Computing', '4', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 228', '2004', 'Geometry and Topology', '2', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 116', '2006', 'Group Theory', '2', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 316', '2009', 'Nonlinear Dynamics', '3', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 221', '2003', 'Algebraic Structures', '2', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('MATH 214', '2001', 'Real Analysis', '3', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 500', '2005', 'My new course', '4', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 215', '2009', 'Public Participation in Planning', '2', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 212', '2009', 'Urban Policy Analysis', '4', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 323', '2005', 'Database Systems', '2', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 125', '2005', 'Computer Graphics', '2', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 111', '2005', 'Web Development', '3', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 216', '2005', 'Mobile App Development', '3', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 337', '2005', 'Web Development', '3', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 127', '2005', 'Human-Computer Interaction', '2', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 133', '2005', 'Mobile App Development', '2', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 118', '2005', 'Cybersecurity', '3', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 126', '2005', 'Cloud Computing', '2', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 122', '2005', 'Compiler Design', '3', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 325', '2005', 'Programming Languages', '4', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 328', '2005', 'Computer Networks', '2', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 113', '2005', 'Cloud Computing', '2', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 124', '2005', 'Human-Computer Interaction', '3', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 332', '2005', 'Machine Learning', '2', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 128', '2005', 'Artificial Intelligence', '3', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 335', '2005', 'Compiler Design', '4', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 313', '2005', 'Web Development', '3', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 321', '2005', 'Artificial Intelligence', '4', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 137', '2005', 'Computer Graphics', '2', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 112', '2005', 'Human-Computer Interaction', '2', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 327', '2005', 'Software Engineering', '2', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 224', '2005', 'Human-Computer Interaction', '2', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 123', '2005', 'Operating Systems', '4', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 236', '2005', 'Database Systems', '3', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 115', '2005', 'Theory of Computation', '4', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 226', '2005', 'Artificial Intelligence', '2', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 117', '2005', 'Computer Graphics', '3', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 135', '2005', 'Computer Graphics', '2', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 235', '2005', 'Computer Architecture', '2', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 314', '2005', 'Machine Learning', '2', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 223', '2005', 'Computer Graphics', '2', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 336', '2005', 'Cybersecurity', '2', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 218', '2005', 'Operating Systems', '3', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 318', '2005', 'Artificial Intelligence', '3', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 131', '2005', 'Computer Networks', '3', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 311', '2005', 'Cybersecurity', '2', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 315', '2005', 'Computer Networks', '4', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 114', '2005', 'Operating Systems', '2', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CSE 116', '2005', 'Theory of Computation', '2', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 234', '2006', 'Antenna Theory', '4', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 235', '2006', 'Digital Signal Processing', '3', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 314', '2006', 'Semiconductor Devices and Circuits', '2', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 121', '2006', 'Power Electronics', '3', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 328', '2006', 'Control Systems Design', '3', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 326', '2006', 'Renewable Energy Systems', '3', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 334', '2006', 'Communication Systems', '2', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 316', '2006', 'Electromagnetic Fields and Waves', '2', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 126', '2006', 'Electromagnetic Fields and Waves', '4', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 315', '2006', 'Control Systems Design', '3', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 133', '2006', 'RF and Microwave Engineering', '3', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 124', '2006', 'Electromagnetic Fields and Waves', '4', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 335', '2006', 'Antenna Theory', '4', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 313', '2006', 'Electric Machines and Drives', '2', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 118', '2006', 'Communication Systems', '2', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 218', '2006', 'Electric Machines and Drives', '2', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 224', '2006', 'Digital Signal Processing', '3', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 338', '2006', 'Control Systems Design', '2', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 311', '2006', 'Antenna Theory', '4', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 122', '2006', 'Electromagnetic Fields and Waves', '2', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 237', '2006', 'VLSI Design', '4', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 215', '2006', 'Antenna Theory', '2', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 125', '2006', 'VLSI Design', '2', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 221', '2006', 'Semiconductor Devices and Circuits', '2', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 222', '2006', '(Electrical Circuit Analysis', '2', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 134', '2006', '(Electrical Circuit Analysis', '2', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 217', '2006', 'Electromagnetic Fields and Waves', '4', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 312', '2006', 'Embedded Systems Design', '3', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 225', '2006', 'Power Electronics', '4', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 327', '2006', 'Electric Machines and Drives', '3', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 212', '2006', 'Digital Signal Processing', '3', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 111', '2006', 'Electronics Fundamentals', '2', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 135', '2006', 'Antenna Theory', '2', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 233', '2006', 'Communication Systems', '3', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 323', '2006', 'Control Systems Design', '3', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 324', '2006', 'Electromagnetic Fields and Waves', '2', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 332', '2006', 'Power Systems Engineering', '4', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 325', '2006', 'Digital Systems Design', '4', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 128', '2006', 'Microelectronics Fabrication', '2', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('EEE 131', '2006', 'Digital Signal Processing', '2', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 132', '2001', 'Quantitative Physiology', '2', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 112', '2001', 'Biomaterials and Tissue Engineering', '3', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 338', '2001', 'Biomolecular Engineering', '4', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 315', '2001', 'Assistive Technologies', '2', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 138', '2001', 'Biomedical Entrepreneurship', '3', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 214', '2001', 'Bionanotechnology', '3', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 135', '2001', 'Imaging for Diagnosis and Therapy', '4', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 123', '2001', 'Medical Product Development', '2', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 115', '2001', 'Biomolecular Engineering', '2', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 127', '2001', 'Clinical Engineering', '4', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 136', '2001', 'Biomaterials and Tissue Engineering', '2', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 325', '2001', 'Medical Data Analysis', '4', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 114', '2001', 'Biomedical Signal Processing', '3', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 222', '2001', 'Bionanotechnology', '3', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 224', '2001', 'Biomedical Instrumentation', '2', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 226', '2001', 'Biomedical Signal Processing', '2', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 117', '2001', 'Biomedical Entrepreneurship', '2', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 323', '2001', 'Healthcare Technology Management', '4', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 238', '2001', 'Medical Device Design', '4', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 231', '2001', 'Biomedical Optics', '2', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 317', '2001', 'Cardiovascular Systems Modeling', '3', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 336', '2001', 'Cardiovascular Systems Modeling', '2', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 232', '2001', 'Medical Device Design', '4', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 327', '2001', 'Pharmacology for Biomedical Engineers', '3', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 337', '2001', 'Neural Engineering', '2', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 313', '2001', 'Biomedical Ethics and Regulations', '2', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 116', '2001', 'Assistive Technologies', '2', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 218', '2001', 'Bionanotechnology', '2', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 216', '2001', 'Medical Robotics', '2', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 331', '2001', 'Medical Data Analysis', '3', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 236', '2001', 'Introduction to Biomedical Engineering', '2', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 221', '2001', 'Biomechanics and Human Movement', '2', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 335', '2001', 'Bioinformatics and Computational Biology', '3', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 133', '2001', 'Assistive Technologies', '2', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 217', '2001', 'Neural Engineering', '3', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 312', '2001', 'Telemedicine and E-Health', '2', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 128', '2001', 'Bioinformatics and Computational Biology', '4', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 311', '2001', 'Medical Product Development', '4', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 125', '2001', 'Biomedical Ethics and Regulations', '2', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('BME 126', '2001', 'Medical Data Analysis', '3', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CE 317', '2003', 'Reinforced Concrete Design', '2', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CE 127', '2003', 'Structural Dynamics', '2', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CE 337', '2003', 'Traffic Engineering', '4', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CE 121', '2003', 'Construction Materials and Testing', '4', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CE 212', '2003', 'Construction Materials and Testing', '2', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CE 112', '2003', 'Structural Health Monitoring', '2', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CE 232', '2003', 'Environmental Impact Assessment', '2', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CE 115', '2003', 'Foundation Engineering', '4', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CE 238', '2003', 'Hydraulic Engineering', '2', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CE 211', '2003', 'Structural Dynamics', '4', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CE 316', '2003', 'Geohazard Mitigation', '3', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CE 331', '2003', 'Construction Materials and Testing', '2', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CE 335', '2003', 'Geotechnical Site Characterization', '2', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CE 323', '2003', 'Steel Structures', '2', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CE 114', '2003', 'Concrete and Masonry Design', '3', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CE 134', '2003', 'Sustainable Infrastructure Design', '4', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CE 122', '2003', 'Transportation Engineering', '2', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CE 213', '2003', 'Reinforced Concrete Design', '2', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CE 128', '2003', 'Geohazard Mitigation', '2', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CE 126', '2003', 'Steel Structures', '4', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CE 125', '2003', 'Geohazard Mitigation', '2', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('CE 236', '2003', 'Structural Health Monitoring', '2', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 113', '2004', 'Engineering Economics and Cost Analysis', '4', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 315', '2004', 'Project Management in Manufacturing', '2', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 238', '2004', 'Decision Analysis and Optimization', '3', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 222', '2004', 'Six Sigma Methodology', '3', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 126', '2004', 'Operations Management', '2', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 117', '2004', 'Operations Management', '3', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 312', '2004', 'Introduction to Industrial and Production Engineering', '4', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 121', '2004', 'Manufacturing System Simulation', '2', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 314', '2004', 'Quality Engineering', '2', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 216', '2004', 'Production Planning and Control', '2', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 225', '2004', 'Industrial Engineering Analytics', '2', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 227', '2004', 'Production Planning and Control', '3', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 321', '2004', 'Industrial Engineering Analytics', '3', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 122', '2004', 'Advanced Materials and Manufacturing', '2', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 218', '2004', 'Sustainable Production Systems', '2', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 224', '2004', 'Operations Research', '2', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 116', '2004', 'Ergonomics and Human Factors Engineering', '4', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 325', '2004', 'Lean Manufacturing', '2', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 221', '2004', 'Introduction to Industrial and Production Engineering', '4', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 228', '2004', 'Ergonomics and Human Factors Engineering', '3', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 317', '2004', 'Decision Analysis and Optimization', '2', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 333', '2004', 'Supply Chain Management', '3', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 332', '2004', 'Industrial Automation', '4', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 235', '2004', 'Supply Chain Management', '4', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 324', '2004', 'Industrial Engineering Analytics', '3', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 212', '2004', 'Operations Research', '3', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 326', '2004', 'Facility Layout and Design', '2', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 334', '2004', 'Decision Analysis and Optimization', '3', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 213', '2004', 'Manufacturing Processes and Systems', '4', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 237', '2004', 'Facility Layout and Design', '3', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 331', '2004', 'Production Scheduling', '2', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 114', '2004', 'Inventory Management', '3', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 137', '2004', 'Project Management in Manufacturing', '2', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 128', '2004', 'Inventory Management', '2', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 131', '2004', 'Inventory Management', '3', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 111', '2004', 'Production Scheduling', '4', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 133', '2004', 'Inventory Management', '4', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 125', '2004', 'Supply Chain Management', '2', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 337', '2002', 'Automotive Engineering', '2', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 214', '2002', 'Combustion and Emissions Control', '2', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 333', '2002', 'Nonlinear Dynamics and Chaos', '3', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 311', '2002', 'Robotics and Automation', '2', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 223', '2002', 'Renewable Energy Systems', '2', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 326', '2002', 'Aerospace Propulsion Systems', '4', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 314', '2002', 'Thermodynamics and Heat Transfer', '4', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 331', '2002', 'Computational Mechanics', '2', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 235', '2002', 'Advanced Manufacturing Technologies', '4', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 111', '2002', 'Nonlinear Dynamics and Chaos', '4', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 234', '2002', 'Machine Design', '2', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 131', '2002', 'Mechanical Behavior of Materials', '2', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 334', '2002', 'Manufacturing Processes', '4', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 217', '2002', 'Engineering Measurements and Instrumentation', '4', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 237', '2002', 'Machine Design', '3', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 134', '2002', 'Mechanical Vibrations', '4', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 112', '2002', 'Composite Materials and Structures', '4', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 227', '2002', 'Materials Science and Engineering', '3', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 136', '2002', 'Solid Mechanics', '3', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 121', '2002', 'Solid Mechanics', '4', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 114', '2002', 'Finite Element Analysis', '2', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 228', '2002', 'Mechanics of Materials', '2', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 315', '2002', 'Internal Combustion Engines', '2', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 215', '2002', 'Nonlinear Dynamics and Chaos', '2', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 327', '2002', 'Finite Element Analysis', '3', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 316', '2002', 'Aerospace Propulsion Systems', '4', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 137', '2002', 'Internal Combustion Engines', '2', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 113', '2002', 'Manufacturing Processes', '3', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 332', '2002', 'Mechatronics and System Integration', '3', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 226', '2002', 'Combustion and Emissions Control', '4', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 118', '2002', 'Nanomaterials and Nanotechnology', '2', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 126', '2002', 'Thermodynamics and Heat Transfer', '2', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 338', '2002', 'Aerospace Propulsion Systems', '3', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 336', '2002', 'Engineering Design and Analysis', '3', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 312', '2002', 'Materials Science and Engineering', '3', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 125', '2002', 'Renewable Energy Systems', '4', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 216', '2002', 'Solid Mechanics', '2', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 213', '2002', 'Introduction to Mechanical Engineering', '4', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 123', '2002', 'Thermodynamics and Heat Transfer', '2', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('ME 325', '2002', 'Mechanical Vibrations', '4', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 326', '2008', 'Reservoir Engineering', '2', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 327', '2008', 'Water Resources Planning and Management', '2', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 112', '2008', 'Environmental Impact Assessment for Water Projects', '2', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 126', '2008', 'Water-Energy Nexus', '3', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 135', '2008', 'Irrigation and Drainage Engineering', '3', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 123', '2008', 'Floodplain Management', '2', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 232', '2008', 'Environmental Fluid Mechanics', '2', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 311', '2008', 'Urban Drainage Systems', '4', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 216', '2008', 'Water Resources Modeling', '2', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 211', '2008', 'Environmental Fluid Mechanics', '3', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 113', '2008', 'Environmental Impact Assessment for Water Projects', '3', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 315', '2008', 'Irrigation and Drainage Engineering', '2', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 132', '2008', 'Coastal Engineering', '2', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 334', '2008', 'Remote Sensing for Hydrology', '2', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 137', '2008', 'Geographic Information Systems (GIS) for Water Resources', '2', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 111', '2008', 'Water Resources Modeling', '4', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 223', '2008', 'Aquatic Ecosystem Restoration', '2', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 213', '2008', 'Environmental Fluid Mechanics', '4', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 336', '2008', 'Aquatic Ecosystem Restoration', '3', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 212', '2008', 'Introduction to Water Resources Engineering', '2', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 331', '2008', 'Water Infrastructure Planning', '3', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 124', '2008', 'Water Treatment Processes', '2', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 116', '2008', 'Groundwater Remediation', '3', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 314', '2008', 'Resilience and Adaptation in Water Resources', '3', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 317', '2008', 'Water Quality Management', '3', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 231', '2008', 'Water Resources Policy and Law', '2', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 312', '2008', 'Resilience and Adaptation in Water Resources', '2', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 131', '2008', 'Geotechnical Aspects of Water Projects', '2', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 227', '2008', 'Water Resources Planning and Management', '2', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 134', '2008', 'River Restoration and Rehabilitation', '2', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 133', '2008', 'Aquatic Ecosystem Restoration', '2', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 136', '2008', 'Geotechnical Aspects of Water Projects', '4', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 234', '2008', 'Water Resources Economics', '3', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 224', '2008', 'Environmental Fluid Mechanics', '2', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 316', '2008', 'Urban Drainage Systems', '2', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 121', '2008', 'Hydraulic Engineering', '2', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 333', '2008', 'Wetland Restoration and Management', '3', 'L1', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 218', '2008', 'Water Resources Planning and Management', '3', 'L4', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 128', '2008', 'Stormwater Management', '4', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('WRE 322', '2008', 'Water and Society', '2', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 137', '2009', 'Disaster Resilient Cities', '2', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 331', '2009', 'Urban Regeneration', '2', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 115', '2009', 'Land Use Planning', '3', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 136', '2009', 'Cultural Heritage and Tourism Planning', '3', 'L3', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 225', '2009', 'Urban Infrastructure Planning', '4', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 231', '2009', 'Regional Development Planning', '4', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 333', '2009', 'Sustainable Urban Planning', '4', 'L3', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 327', '2009', 'Urban Infrastructure Planning', '2', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 235', '2009', 'Landscape and Open Space Planning', '2', 'L4', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 122', '2009', 'Urban Policy Analysis', '2', 'L1', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('URP 222', '2009', 'Transit-Oriented Development', '4', 'L2', 'T1');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 313', '2004', 'Manufacturing Processes and Systems', '4', 'L2', 'T2');
INSERT INTO "COURSE" ("COURSE_ID", "DEPT_ID", "TITLE", "CREDIT", "LEVEL", "TERM") VALUES ('IPE 136', '2004', 'Quality Engineering', '2', 'L2', 'T2');
