INSERT INTO "DEPARTMENT" ("DEPARTMENT_ID", "DEPARTMENT_NAME") VALUES ('2005', 'CSE');
INSERT INTO "DEPARTMENT" ("DEPARTMENT_ID", "DEPARTMENT_NAME") VALUES ('2006', 'EEE');
INSERT INTO "DEPARTMENT" ("DEPARTMENT_ID", "DEPARTMENT_NAME") VALUES ('2001', 'BME');
INSERT INTO "DEPARTMENT" ("DEPARTMENT_ID", "DEPARTMENT_NAME") VALUES ('2002', 'ME');
INSERT INTO "DEPARTMENT" ("DEPARTMENT_ID", "DEPARTMENT_NAME") VALUES ('2003', 'CE');
INSERT INTO "DEPARTMENT" ("DEPARTMENT_ID", "DEPARTMENT_NAME") VALUES ('2004', 'IPE');
INSERT INTO "DEPARTMENT" ("DEPARTMENT_ID", "DEPARTMENT_NAME") VALUES ('2008', 'WRE');
INSERT INTO "DEPARTMENT" ("DEPARTMENT_ID", "DEPARTMENT_NAME") VALUES ('2009', 'URP');
