INSERT INTO "DUES" ("DUE_ID", "DESCRIPTION", "AMOUNT") VALUES ('3', 'Registration Fee', '5000');
INSERT INTO "DUES" ("DUE_ID", "DESCRIPTION", "AMOUNT") VALUES ('1', 'Hall Fee', '3000');
INSERT INTO "DUES" ("DUE_ID", "DESCRIPTION", "AMOUNT") VALUES ('2', 'Dining Fee', '3000');
INSERT INTO "DUES" ("DUE_ID", "DESCRIPTION", "AMOUNT") VALUES ('21', 'Hall Fee2', '3000');
