INSERT INTO "ENROLLMENT" ("STUDENT_ID", "COURSE_ID", "GRADE", "STATUS") VALUES ('4005', 'WRE 123', NULL, 'waiting for approval');
INSERT INTO "ENROLLMENT" ("STUDENT_ID", "COURSE_ID", "GRADE", "STATUS") VALUES ('4005', 'WRE 223', NULL, 'waiting for approval');
INSERT INTO "ENROLLMENT" ("STUDENT_ID", "COURSE_ID", "GRADE", "STATUS") VALUES ('4005', 'WRE 231', NULL, 'waiting for approval');
INSERT INTO "ENROLLMENT" ("STUDENT_ID", "COURSE_ID", "GRADE", "STATUS") VALUES ('4005', 'WRE 312', NULL, 'waiting for approval');
INSERT INTO "ENROLLMENT" ("STUDENT_ID", "COURSE_ID", "GRADE", "STATUS") VALUES ('4005', 'MATH 311', NULL, 'waiting for approval');
INSERT INTO "ENROLLMENT" ("STUDENT_ID", "COURSE_ID", "GRADE", "STATUS") VALUES ('4005', 'WRE 126', NULL, 'waiting for approval');
INSERT INTO "ENROLLMENT" ("STUDENT_ID", "COURSE_ID", "GRADE", "STATUS") VALUES ('4005', 'WRE 133', NULL, 'waiting for approval');
INSERT INTO "ENROLLMENT" ("STUDENT_ID", "COURSE_ID", "GRADE", "STATUS") VALUES ('4005', 'WRE 136', NULL, 'waiting for approval');
