INSERT INTO "SCHOLARSHIP" ("SCHOLARSHIP_TITLE", "DESCRIPTION", "SCHOLARSHIP_ID", "AMOUNT") VALUES ('GRGWEUIRWUE', 'EWRRWERWR', '4', '3434');
INSERT INTO "SCHOLARSHIP" ("SCHOLARSHIP_TITLE", "DESCRIPTION", "SCHOLARSHIP_ID", "AMOUNT") VALUES ('Merit Scholarship', 'Given for excellient performance in studies', '2', '3000');
INSERT INTO "SCHOLARSHIP" ("SCHOLARSHIP_TITLE", "DESCRIPTION", "SCHOLARSHIP_ID", "AMOUNT") VALUES ('TAHERA', 'wewrerewrwe', '3', '3434');
INSERT INTO "SCHOLARSHIP" ("SCHOLARSHIP_TITLE", "DESCRIPTION", "SCHOLARSHIP_ID", "AMOUNT") VALUES ('title', 'scholarship', '5', '2345');
INSERT INTO "SCHOLARSHIP" ("SCHOLARSHIP_TITLE", "DESCRIPTION", "SCHOLARSHIP_ID", "AMOUNT") VALUES ('title1', 'd1', '6', '2300');
