INSERT INTO "STUDENT_SCHOLARSHIP" ("STUDENT_ID", "SCHOLARSHIP_ID", "STATUS", "TEACHER_ID") VALUES ('4324', '2', 'approved', '8005');
INSERT INTO "STUDENT_SCHOLARSHIP" ("STUDENT_ID", "SCHOLARSHIP_ID", "STATUS", "TEACHER_ID") VALUES ('4124', '4', 'approved', '8016');
INSERT INTO "STUDENT_SCHOLARSHIP" ("STUDENT_ID", "SCHOLARSHIP_ID", "STATUS", "TEACHER_ID") VALUES ('4005', '4', 'waiting for approval', '8016');
